image: node:10.15.3
pipelines:
  default:
      - step:
          name: Build and Test
          caches:
            - node
          script:
            - apt-get update && apt-get install -yq libgconf-2-4
              - >
              apt-get update && apt-get install -y wget --no-install-recommends && \
              wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -  && \
              sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' && \
              apt-get update && \
              apt-get install -y google-chrome-unstable fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst ttf-freefont --no-install-recommends
              - cd webui
              - npm install
              - npm run test:prod
              - npm run build
          artifacts:
            - dist/**
